heat_template_version: 2013-05-23

description: Template to deploy a RabbitMQ cluster

parameters:
    node-flavor:
        description: Rackspace Cloud Server flavor
        type: string
        default: 2GB Standard Instance
        constraints:
        - allowed_values:
          - 2 GB Performance
          - 4 GB Performance
          - 8 GB Performance
          - 15 GB Performance
          - 30 GB Performance
          - 512MB Standard Instance
          - 1GB Standard Instance
          - 2GB Standard Instance
          - 4GB Standard Instance
          - 8GB Standard Instance
          - 15GB Standard Instance
          - 30GB Standard Instance
          description: |
            Must be a valid Rackspace Cloud Server flavor for the region you have
            selected to deploy into

    size:
        type: number
        default: 2
        description: How many initial nodes to start the cluster with
        constraints:
         -  range: { min: 1, max: 5 }
            description: To begin with, at most 5 nodes can be provisioned.

    rmq_admin_user:
        description: username for the rabbitmq account
        type: string
        default: admin

    rmq_admin_pass:
        description: password for the rabbitmq account
        type: string
        default: password

resources:
    ssh-key:
        type: "OS::Nova::KeyPair"
        properties:
            name: {get_param: "OS::stack_id"}
            save_private_key: true

    master-node:
        type: Rackspace::Cloud::Server
        properties:
            name: rmqmaster
            flavor: { get_param: node-flavor}
            image: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
            key_name: { get_resource: ssh-key }
            user_data:
                str_replace:
                    template: |
                        echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
                        wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
                        apt-key add rabbitmq-signing-key-public.asc
                        apt-get update
                        apt-get upgrade -y
                        apt-get install -y rabbitmq-server sshpass
                        rabbitmqctl add_user rmquser rmqpassword
                        rabbitmqctl set_user_tags rmquser administrator
                        rabbitmqctl stop
                        rabbitmq-plugins enable rabbitmq_management
                        iptables -I INPUT 1 -i eth0 -p tcp --dport 15672 -j ACCEPT
                        iptables-save
                        service rabbitmq-server start


                    params:
                        rmquser: { get_param: rmq_admin_user}
                        rmqpassword: { get_param: rmq_admin_pass}

    cluster-nodes:
        type: "OS::Heat::ResourceGroup"
        properties:
            count: { get_param: size }
            resource_def:
                type: https://gist.githubusercontent.com/abettadapur/0ed3668405b04bc2c185/raw/rabbit.yaml  #needs to be remote for some fun reason. Will keep investigating
                properties:
                    server_flavor: {get_param: node-flavor}
                    ssh_keypair_name: {get_resource: ssh-key}
                    ssh_private_key: { get_attr: [ssh-key, private_key]}
                    rmq_master_host: rmqmaster
                    rmq_master_ip: {get_attr: [master-node, privateIPv4]}


    cluster-lb:
        type: "Rackspace::Cloud::LoadBalancer"
        depends_on: cluster-nodes
        properties:
            name: RMQ Load Balancer
            nodes:
             -  addresses: { get_attr: [cluster-nodes, rmq-private-ip]}
                port: 5672
                condition: ENABLED
            protocol: TCP
            port: 5672
            virtualIps: [{type: PUBLIC, ipVersion: IPV4}]

outputs:
    lb_public_ip:
        description: The address of the load balancer
        value: { get_attr: [cluster-lb, PublicIp] }

    node_ips:
        description: The addresses of the RabbitMQ nodes
        value: { get_attr: [cluster-nodes, rmq-server-ip] }

    admin_passwords:
        value: { get_attr: [cluster-nodes, rmq-root-pass]}

    masterdetails:
        value: {get_attr: [master-node, show]}

    masterip:
        value: {get_attr: [master-node, accessIPv4]}

    clusterdetails:
        value: {get_attr: [cluster-nodes, show]}

    sshkey:
        value: {get_attr: [ssh-key, private_key]}
